# Source:
# - https://github.com/leotorres114/chicagomapbot/blob/main/.github/workflows/chimapbot.yml
# - https://github.com/matt-dray/londonmapbot/blob/master/.github/workflows/londonmapbot.yml
# - https://github.com/roberer/esmapbot/blob/master/.github/workflows/esmapbot.yml
# - https://github.com/r-lib/actions/tree/v2-branch/setup-r
# - https://crontab.guru/
# - https://github.com/CredibilityLab/groundhog/blob/v1.5.0/R/get.groundhog.folder.R#L23
name: portugalmapbot

on:
  push:
    branches:
      - master

jobs:
  portugalmapbot-post:
    runs-on: macos-10.15
    env:
      TWITTER_CONSUMER_API_KEY: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
      TWITTER_CONSUMER_API_SECRET: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
      TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
      MAPBOX_PUBLIC_ACCESS_TOKEN: ${{ secrets.MAPBOX_PUBLIC_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '3.6.3'
      - name: Install groundhog package
        run: Rscript -e 'install.packages("groundhog", dependencies = TRUE)'
      - name: Create the main groundhog folder early to avoid manual confirmation later
        run: mkdir ~/R_groundhog
      - name: Create and post tweet
        run: Rscript portugalmapbot-tweet.R
